name: PhotoScope CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Source/PhotoScopeConsole/PhotoScopeConsole.sln
      Test_Project_Path: your-test-project-path

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.0.6

    - name: Restore Nuget packages
      run: nuget restore $env:Solution_Name

    - name: Build the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
      
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .
        
    - name: Run UnitTests
      run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe  Source/PhotoScopeConsole/tst/PhotoScope.BusinessLogic.Tests/bin/Debug/PhotoScope.BusinessLogic.Tests.dll
